### ISSUE TITLE
Armv7: LDAEX/STLEX disassembled as LDREX/STREX

### ISSUE THREAD

**Issue by MartijnB** [Vector35/arch-armv7#14]
In a binary I encountered the following instructions:

10006208  9f2e93e1   ldrex   r2, [r3]
1000620c  000052e3   cmp     r2, #0
10006210  0200001a   bne     0x10006220

10006214  910e83e1   strex   r0, r1, [r3]
10006218  000050e3   cmp     r0, #0
1000621c  f9ffff1a   bne     0x10006208

Capstone fails to disassemble these instructions at all.

@withzombies pointed out that ORR also doesn't make sense and he was right. This instruction is incorrectly decoded by pretty much every disassembler. It seems so far only objdump is correct:

    6208:       e1932e9f        ldaex   r2, [r3]
    620c:       e3520000        cmp     r2, #0
    6210:       1a000002        bne     6220 <lseek+0x828>
    6214:       e1830e91        stlex   r0, r1, [r3]
    6218:       e3500000        cmp     r0, #0
    621c:       1afffff9        bne     6208 <lseek+0x810>

**Comment by lwerdna** [comment]
Our ARMv7 disassembler was very permissive, and would disassemble to ldrex and strex even when one of the fields specified as `(1)(1)(1)(1)` was not actually 1111. When ARMv8 came, I think ARMv7's instructions got augmented, and that fields is specialized to `(1)(1)10` for ldaex, strex and friends and `(1)(1)00` for stl. I hope the latest commits resolve everything reported here. I your test cases and others atop test.py. Feel free to reopen the ticket if it's not resolved.
