### ISSUE TITLE
ELF Relocation failure on armv7

### ISSUE THREAD

**Issue by psifertex** [Vector35/arch-armv7#61]
### Discussed in https://github.com/Vector35/binaryninja-api/discussions/2911

<div type='discussions-op-text'>

<sup>Originally posted by **f8lft** February  1, 2022</sup>
ELF relocations are getting applied to the binary during analysis?</div>

Relocation mis-applied at 4f942a24. You'll see the "c0 65 27 9f" instead of "c0 e5 93 4f".

[libsierra_nv.so.0.zip](https://github.com/Vector35/binaryninja-api/files/7979146/libsierra_nv.so.0.zip)

**Comment by plafosse** [comment]
Here is some code that implements this functionality: https://github.com/NationalSecurityAgency/ghidra/blob/c2510e5ab03b9aa8b88e34af65e5694701f799f7/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/ElfProgramBuilder.java#L3006

**Comment by lwerdna** [comment]
> Relocation mis-applied at 4f942a24. You'll see the "c0 65 27 9f" instead of "c0 e5 93 4f".

Double checking: Did you mean this the other way around? The bytes `c0 e5 93 4f` appear in the file at 9A24:

```
│00009A20 A0 E3 93 4F C0 E5 93 4F C8 E5 93 4F D0 E5 93 4F │▒│...O...O...O...O│
│00009A30 00 00 00 00 D8 E5 93 4F E0 E5 93 4F 00 00 00 00 │▒│.......O...O....│
```

And also in BinaryNinja at 4f942a24 (after mapping). The issue claims we should see _different_ bytes`c0 65 27 9f` if relocations were applied correctly, right?

**Comment by lwerdna** [comment]
If you set the type of the `4f942a24: c0 e5 9f 4f` to `char *` you should see it reference some strings: a little evidence the relocation is applied ok.

![strings](https://user-images.githubusercontent.com/474191/185843651-3ada0c06-d85f-496c-9e9f-ac01dd768dc0.png)

Note: without rebasing, the binary should default load to 0x4f938000 and the relocation applies no adjustment.
